id: P002895
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:26:57.096441
source_metadata:
  id: bdr:W1KG3816
  title: ངེས་ཤེས་རིན་པོ་ཆེའི་སྒྲོན་མེའི་རྣམ་བཤད་འོད་ཟེར་དྲི་མེད
  author: ''
  volumes:
    0804f411215a4a62883a9d1cb8f7ebbf:
      image_group_id: I1KG3861
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
